e116_racecar:
  ros__parameters:
    servo_min: 21.2
    servo_max: 38.1
    servo_center: 29.3
    motor_forward_start: 30.11
    motor_backward_start: 30.11
    motor_range: 2.5
    speed_scale: 0.75
    speed_dead_area: 0.2
    angle_scale: 25.0

keyJoy:
  ros__parameters: {}
    
keyJoyTerminal:
  ros__parameters: {}

